include /etc/nginx/snippets/upstreams.conf;

server {
    listen 80;
    server_name _;
    client_max_body_size 10m;
    resolver 127.0.0.11 valid=10s ipv6=off;

    include /etc/nginx/snippets/security-headers.conf;
    include /etc/nginx/snippets/gateway-locations.conf;
}
