services:
  app:
    build: ./
    env_file: ./.env
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2"
    depends_on:
      - rabbitmq
      - mongodb
      - localstack

  rabbitmq:
      image: rabbitmq:4.1-management
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  mongodb:
    image: bitnami/mongodb:5.0
    environment:
      - MONGODB_ROOT_USER=${MONGODB_ROOT_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/bitnami/mongodb

  localstack:
    image: localstack/localstack:2.1
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION_NAME=${S3_REGION_NAME}
    volumes:
      - ./localstack_data:/tmp/localstack

volumes:
  mongodb_data:
