user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    log_format gateway '$remote_addr - [$time_local] "$request" '
                       '$status $body_bytes_sent '
                       'rt=$request_time uct=$upstream_connect_time '
                       'uht=$upstream_header_time urt=$upstream_response_time '
                       '"$http_user_agent"';

    access_log /var/log/nginx/access.log gateway;

    sendfile on;
    keepalive_timeout 65;

    limit_req_status 429;
    limit_req_log_level warn;

    limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=10r/m;

    map $request_method $practice_limit_key {
        POST     $binary_remote_addr;
        default  "";
    }

    limit_req_zone $practice_limit_key zone=practice_limit:10m rate=10r/m;

    include /etc/nginx/conf.d/*.conf;
}
