from typing import Any, Protocol

from shared_models.practice.attempt import ExerciseAttempt
from shared_models.practice.plan import PlanStatus, PracticePlan
from shared_models.practice.profile import UserPracticeProfile


class IPlanRepository(Protocol):
    async def create_plan(self, plan: PracticePlan) -> PracticePlan: ...

    async def get_plan(self, plan_id: str, user_id: str) -> PracticePlan | None: ...

    async def get_plan_by_id(self, plan_id: str) -> PracticePlan | None: ...

    async def get_plan_by_interview_session(self, interview_session_id: str) -> PracticePlan | None: ...

    async def update_plan(self, plan_id: str, update_data: dict[str, Any]) -> bool: ...

    async def list_plans(
        self,
        user_id: str,
        *,
        skip: int = 0,
        limit: int = 20,
        status: PlanStatus | None = None,
    ) -> list[PracticePlan]: ...

    async def ensure_indexes(self) -> None: ...


class IAttemptRepository(Protocol):
    async def upsert_attempt(self, attempt: ExerciseAttempt) -> ExerciseAttempt: ...

    async def get_attempt(self, user_id: str, plan_id: str, exercise_id: str) -> ExerciseAttempt | None: ...

    async def list_attempts(self, user_id: str, plan_id: str, exercise_id: str) -> list[ExerciseAttempt]: ...

    async def list_plan_attempts(self, user_id: str, plan_id: str) -> list[ExerciseAttempt]: ...

    async def ensure_indexes(self) -> None: ...


class IProfileRepository(Protocol):
    async def get_profile(self, user_id: str) -> UserPracticeProfile | None: ...

    async def upsert_profile(self, profile: UserPracticeProfile) -> UserPracticeProfile: ...

    async def ensure_indexes(self) -> None: ...
