"""Add invitations, attempts, decisions, audit log, and event idempotency."""
from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "07a8b9c0d1e2"
down_revision: Union[str, None] = "f6a7b8c9d0e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.create_table("candidate_invitations", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("organization_id", sa.Uuid(), nullable=False), sa.Column("vacancy_id", sa.Uuid(), nullable=False), sa.Column("template_id", sa.Uuid(), nullable=False), sa.Column("template_version", sa.Integer(), nullable=False), sa.Column("token_hash", sa.String(128), nullable=False, unique=True), sa.Column("candidate_email_normalized", sa.String(320), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("max_attempts", sa.Integer(), nullable=False, server_default="1"), sa.Column("attempts_started", sa.Integer(), nullable=False, server_default="0"), sa.Column("status", sa.String(16), nullable=False, server_default="created"), sa.Column("created_by", sa.Uuid(), nullable=False), sa.Column("revoked_at", sa.DateTime(timezone=True)), sa.Column("revoked_by", sa.Uuid()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("TIMEZONE('utc', now())")), sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]), sa.ForeignKeyConstraint(["vacancy_id"], ["vacancies.id"]), sa.ForeignKeyConstraint(["template_id"], ["assessment_templates.id"]), sa.ForeignKeyConstraint(["created_by"], ["users.id"]), sa.ForeignKeyConstraint(["revoked_by"], ["users.id"]))
    op.create_index("ix_candidate_invitations_vacancy_status", "candidate_invitations", ["vacancy_id", "status"])
    op.create_table("candidate_attempts", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("invitation_id", sa.Uuid(), nullable=False), sa.Column("candidate_email_normalized", sa.String(320), nullable=False), sa.Column("candidate_display_name", sa.String(160)), sa.Column("consent_version", sa.String(64), nullable=False), sa.Column("consented_at", sa.DateTime(timezone=True), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="created"), sa.Column("cv_correlation_id", sa.Uuid(), unique=True), sa.Column("interview_session_id", sa.String(128)), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("failure_code", sa.String(64)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("TIMEZONE('utc', now())")), sa.ForeignKeyConstraint(["invitation_id"], ["candidate_invitations.id"]))
    op.create_index("ix_candidate_attempts_invitation_status", "candidate_attempts", ["invitation_id", "status"])
    op.create_table("human_decisions", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("attempt_id", sa.Uuid(), nullable=False, unique=True), sa.Column("decision", sa.String(24), nullable=False), sa.Column("private_note", sa.Text()), sa.Column("actor_user_id", sa.Uuid(), nullable=False), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("TIMEZONE('utc', now())")), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("TIMEZONE('utc', now())")), sa.ForeignKeyConstraint(["attempt_id"], ["candidate_attempts.id"]), sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"]))
    op.create_table("audit_log", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("actor_type", sa.String(32), nullable=False), sa.Column("actor_id", sa.Uuid()), sa.Column("action", sa.String(96), nullable=False), sa.Column("organization_id", sa.Uuid()), sa.Column("vacancy_id", sa.Uuid()), sa.Column("invitation_id", sa.Uuid()), sa.Column("attempt_id", sa.Uuid()), sa.Column("before", postgresql.JSONB()), sa.Column("after", postgresql.JSONB()), sa.Column("request_metadata", postgresql.JSONB()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("TIMEZONE('utc', now())")))
    op.create_table("processed_events", sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("consumer_name", sa.String(96), nullable=False), sa.Column("event_id", sa.Uuid(), nullable=False), sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("TIMEZONE('utc', now())")), sa.UniqueConstraint("consumer_name", "event_id", name="uq_processed_events_consumer_event"))

def downgrade() -> None:
    op.drop_table("processed_events"); op.drop_table("audit_log"); op.drop_table("human_decisions"); op.drop_index("ix_candidate_attempts_invitation_status", table_name="candidate_attempts"); op.drop_table("candidate_attempts"); op.drop_index("ix_candidate_invitations_vacancy_status", table_name="candidate_invitations"); op.drop_table("candidate_invitations")
