apiVersion: v1
kind: Service
metadata:
  name: user-management
  labels:
    app.kubernetes.io/name: ai-interview-tutor
    app.kubernetes.io/component: user-management
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app.kubernetes.io/name: ai-interview-tutor
    app.kubernetes.io/component: user-management
